version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ecommerce.db
      - SECRET_KEY=your-secret-key
    volumes:
      - .:/app